# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos.Networking.Platform.Requests.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos.Networking.Platform.Requests.proto',
  package='POGOProtos.Networking.Platform.Requests',
  syntax='proto3',
  serialized_pb=_b('\n-POGOProtos.Networking.Platform.Requests.proto\x12\'POGOProtos.Networking.Platform.Requests\"0\n\x15\x42uyItemAndroidRequest\x12\x17\n\x0f\x62uy_item_intent\x18\x01 \x01(\t\"*\n\x17\x42uyItemPokeCoinsRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\"<\n\x1dSendEncryptedSignatureRequest\x12\x1b\n\x13\x65ncrypted_signature\x18\x01 \x01(\x0c\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BUYITEMANDROIDREQUEST = _descriptor.Descriptor(
  name='BuyItemAndroidRequest',
  full_name='POGOProtos.Networking.Platform.Requests.BuyItemAndroidRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='buy_item_intent', full_name='POGOProtos.Networking.Platform.Requests.BuyItemAndroidRequest.buy_item_intent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=138,
)


_BUYITEMPOKECOINSREQUEST = _descriptor.Descriptor(
  name='BuyItemPokeCoinsRequest',
  full_name='POGOProtos.Networking.Platform.Requests.BuyItemPokeCoinsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='POGOProtos.Networking.Platform.Requests.BuyItemPokeCoinsRequest.item_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=182,
)


_SENDENCRYPTEDSIGNATUREREQUEST = _descriptor.Descriptor(
  name='SendEncryptedSignatureRequest',
  full_name='POGOProtos.Networking.Platform.Requests.SendEncryptedSignatureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encrypted_signature', full_name='POGOProtos.Networking.Platform.Requests.SendEncryptedSignatureRequest.encrypted_signature', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=244,
)

DESCRIPTOR.message_types_by_name['BuyItemAndroidRequest'] = _BUYITEMANDROIDREQUEST
DESCRIPTOR.message_types_by_name['BuyItemPokeCoinsRequest'] = _BUYITEMPOKECOINSREQUEST
DESCRIPTOR.message_types_by_name['SendEncryptedSignatureRequest'] = _SENDENCRYPTEDSIGNATUREREQUEST

BuyItemAndroidRequest = _reflection.GeneratedProtocolMessageType('BuyItemAndroidRequest', (_message.Message,), dict(
  DESCRIPTOR = _BUYITEMANDROIDREQUEST,
  __module__ = 'POGOProtos.Networking.Platform.Requests_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Platform.Requests.BuyItemAndroidRequest)
  ))
_sym_db.RegisterMessage(BuyItemAndroidRequest)

BuyItemPokeCoinsRequest = _reflection.GeneratedProtocolMessageType('BuyItemPokeCoinsRequest', (_message.Message,), dict(
  DESCRIPTOR = _BUYITEMPOKECOINSREQUEST,
  __module__ = 'POGOProtos.Networking.Platform.Requests_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Platform.Requests.BuyItemPokeCoinsRequest)
  ))
_sym_db.RegisterMessage(BuyItemPokeCoinsRequest)

SendEncryptedSignatureRequest = _reflection.GeneratedProtocolMessageType('SendEncryptedSignatureRequest', (_message.Message,), dict(
  DESCRIPTOR = _SENDENCRYPTEDSIGNATUREREQUEST,
  __module__ = 'POGOProtos.Networking.Platform.Requests_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Platform.Requests.SendEncryptedSignatureRequest)
  ))
_sym_db.RegisterMessage(SendEncryptedSignatureRequest)


# @@protoc_insertion_point(module_scope)
