# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos.Networking.Platform.Responses.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from POGOProtos.Data import Player_pb2 as POGOProtos_dot_Data_dot_Player__pb2
POGOProtos_dot_Enums__pb2 = POGOProtos_dot_Data_dot_Player__pb2.POGOProtos_dot_Enums__pb2
from POGOProtos.Inventory import Item_pb2 as POGOProtos_dot_Inventory_dot_Item__pb2

from POGOProtos.Data.Player_pb2 import *
from POGOProtos.Inventory.Item_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos.Networking.Platform.Responses.proto',
  package='POGOProtos.Networking.Platform.Responses',
  syntax='proto3',
  serialized_pb=_b('\n.POGOProtos.Networking.Platform.Responses.proto\x12(POGOProtos.Networking.Platform.Responses\x1a\x1cPOGOProtos.Data.Player.proto\x1a\x1fPOGOProtos.Inventory.Item.proto\"\xad\x01\n\x16\x42uyItemAndroidResponse\x12W\n\x06result\x18\x01 \x01(\x0e\x32G.POGOProtos.Networking.Platform.Responses.BuyItemAndroidResponse.Status\x12\x16\n\x0epurchase_token\x18\x02 \x01(\t\"\"\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\"\xb3\x01\n\x18\x42uyItemPokeCoinsResponse\x12Y\n\x06result\x18\x01 \x01(\x0e\x32I.POGOProtos.Networking.Platform.Responses.BuyItemPokeCoinsResponse.Status\"<\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x18\n\x14NOT_ENOUGH_POKECOINS\x10\x03\"\xbc\x05\n\x15GetStoreItemsResponse\x12V\n\x06status\x18\x01 \x01(\x0e\x32\x46.POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.Status\x12X\n\x05items\x18\x02 \x03(\x0b\x32I.POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.StoreItem\x12;\n\x11player_currencies\x18\x03 \x03(\x0b\x32 .POGOProtos.Data.Player.Currency\x12\x10\n\x08unknown4\x18\x04 \x01(\t\x1a\xfe\x02\n\tStoreItem\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x0e\n\x06is_iap\x18\x02 \x01(\x08\x12\x39\n\x0f\x63urrency_to_buy\x18\x03 \x01(\x0b\x32 .POGOProtos.Data.Player.Currency\x12\x39\n\x0fyields_currency\x18\x04 \x01(\x0b\x32 .POGOProtos.Data.Player.Currency\x12\x38\n\x0byields_item\x18\x05 \x01(\x0b\x32#.POGOProtos.Inventory.Item.ItemData\x12\x61\n\x04tags\x18\x06 \x03(\x0b\x32S.POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.StoreItem.TagsEntry\x12\x10\n\x08unknown7\x18\x07 \x01(\x05\x1a+\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"!\n\x06Status\x12\r\n\tUNDEFINED\x10\x00\x12\x08\n\x04OKAY\x10\x01\"2\n\x1eSendEncryptedSignatureResponse\x12\x10\n\x08received\x18\x01 \x01(\x08P\x00P\x01\x62\x06proto3')
  ,
  dependencies=[POGOProtos_dot_Data_dot_Player__pb2.DESCRIPTOR,POGOProtos_dot_Inventory_dot_Item__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_BUYITEMANDROIDRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='POGOProtos.Networking.Platform.Responses.BuyItemAndroidResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=295,
  serialized_end=329,
)
_sym_db.RegisterEnumDescriptor(_BUYITEMANDROIDRESPONSE_STATUS)

_BUYITEMPOKECOINSRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='POGOProtos.Networking.Platform.Responses.BuyItemPokeCoinsResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_ENOUGH_POKECOINS', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=451,
  serialized_end=511,
)
_sym_db.RegisterEnumDescriptor(_BUYITEMPOKECOINSRESPONSE_STATUS)

_GETSTOREITEMSRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OKAY', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=1181,
  serialized_end=1214,
)
_sym_db.RegisterEnumDescriptor(_GETSTOREITEMSRESPONSE_STATUS)


_BUYITEMANDROIDRESPONSE = _descriptor.Descriptor(
  name='BuyItemAndroidResponse',
  full_name='POGOProtos.Networking.Platform.Responses.BuyItemAndroidResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='POGOProtos.Networking.Platform.Responses.BuyItemAndroidResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='purchase_token', full_name='POGOProtos.Networking.Platform.Responses.BuyItemAndroidResponse.purchase_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BUYITEMANDROIDRESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=329,
)


_BUYITEMPOKECOINSRESPONSE = _descriptor.Descriptor(
  name='BuyItemPokeCoinsResponse',
  full_name='POGOProtos.Networking.Platform.Responses.BuyItemPokeCoinsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='POGOProtos.Networking.Platform.Responses.BuyItemPokeCoinsResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BUYITEMPOKECOINSRESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=332,
  serialized_end=511,
)


_GETSTOREITEMSRESPONSE_STOREITEM_TAGSENTRY = _descriptor.Descriptor(
  name='TagsEntry',
  full_name='POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.StoreItem.TagsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.StoreItem.TagsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.StoreItem.TagsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1136,
  serialized_end=1179,
)

_GETSTOREITEMSRESPONSE_STOREITEM = _descriptor.Descriptor(
  name='StoreItem',
  full_name='POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.StoreItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.StoreItem.item_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_iap', full_name='POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.StoreItem.is_iap', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currency_to_buy', full_name='POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.StoreItem.currency_to_buy', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yields_currency', full_name='POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.StoreItem.yields_currency', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yields_item', full_name='POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.StoreItem.yields_item', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.StoreItem.tags', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown7', full_name='POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.StoreItem.unknown7', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GETSTOREITEMSRESPONSE_STOREITEM_TAGSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=797,
  serialized_end=1179,
)

_GETSTOREITEMSRESPONSE = _descriptor.Descriptor(
  name='GetStoreItemsResponse',
  full_name='POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='items', full_name='POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_currencies', full_name='POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.player_currencies', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown4', full_name='POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.unknown4', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GETSTOREITEMSRESPONSE_STOREITEM, ],
  enum_types=[
    _GETSTOREITEMSRESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=514,
  serialized_end=1214,
)


_SENDENCRYPTEDSIGNATURERESPONSE = _descriptor.Descriptor(
  name='SendEncryptedSignatureResponse',
  full_name='POGOProtos.Networking.Platform.Responses.SendEncryptedSignatureResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='received', full_name='POGOProtos.Networking.Platform.Responses.SendEncryptedSignatureResponse.received', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1216,
  serialized_end=1266,
)

_BUYITEMANDROIDRESPONSE.fields_by_name['result'].enum_type = _BUYITEMANDROIDRESPONSE_STATUS
_BUYITEMANDROIDRESPONSE_STATUS.containing_type = _BUYITEMANDROIDRESPONSE
_BUYITEMPOKECOINSRESPONSE.fields_by_name['result'].enum_type = _BUYITEMPOKECOINSRESPONSE_STATUS
_BUYITEMPOKECOINSRESPONSE_STATUS.containing_type = _BUYITEMPOKECOINSRESPONSE
_GETSTOREITEMSRESPONSE_STOREITEM_TAGSENTRY.containing_type = _GETSTOREITEMSRESPONSE_STOREITEM
_GETSTOREITEMSRESPONSE_STOREITEM.fields_by_name['currency_to_buy'].message_type = POGOProtos_dot_Data_dot_Player__pb2._CURRENCY
_GETSTOREITEMSRESPONSE_STOREITEM.fields_by_name['yields_currency'].message_type = POGOProtos_dot_Data_dot_Player__pb2._CURRENCY
_GETSTOREITEMSRESPONSE_STOREITEM.fields_by_name['yields_item'].message_type = POGOProtos_dot_Inventory_dot_Item__pb2._ITEMDATA
_GETSTOREITEMSRESPONSE_STOREITEM.fields_by_name['tags'].message_type = _GETSTOREITEMSRESPONSE_STOREITEM_TAGSENTRY
_GETSTOREITEMSRESPONSE_STOREITEM.containing_type = _GETSTOREITEMSRESPONSE
_GETSTOREITEMSRESPONSE.fields_by_name['status'].enum_type = _GETSTOREITEMSRESPONSE_STATUS
_GETSTOREITEMSRESPONSE.fields_by_name['items'].message_type = _GETSTOREITEMSRESPONSE_STOREITEM
_GETSTOREITEMSRESPONSE.fields_by_name['player_currencies'].message_type = POGOProtos_dot_Data_dot_Player__pb2._CURRENCY
_GETSTOREITEMSRESPONSE_STATUS.containing_type = _GETSTOREITEMSRESPONSE
DESCRIPTOR.message_types_by_name['BuyItemAndroidResponse'] = _BUYITEMANDROIDRESPONSE
DESCRIPTOR.message_types_by_name['BuyItemPokeCoinsResponse'] = _BUYITEMPOKECOINSRESPONSE
DESCRIPTOR.message_types_by_name['GetStoreItemsResponse'] = _GETSTOREITEMSRESPONSE
DESCRIPTOR.message_types_by_name['SendEncryptedSignatureResponse'] = _SENDENCRYPTEDSIGNATURERESPONSE

BuyItemAndroidResponse = _reflection.GeneratedProtocolMessageType('BuyItemAndroidResponse', (_message.Message,), dict(
  DESCRIPTOR = _BUYITEMANDROIDRESPONSE,
  __module__ = 'POGOProtos.Networking.Platform.Responses_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Platform.Responses.BuyItemAndroidResponse)
  ))
_sym_db.RegisterMessage(BuyItemAndroidResponse)

BuyItemPokeCoinsResponse = _reflection.GeneratedProtocolMessageType('BuyItemPokeCoinsResponse', (_message.Message,), dict(
  DESCRIPTOR = _BUYITEMPOKECOINSRESPONSE,
  __module__ = 'POGOProtos.Networking.Platform.Responses_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Platform.Responses.BuyItemPokeCoinsResponse)
  ))
_sym_db.RegisterMessage(BuyItemPokeCoinsResponse)

GetStoreItemsResponse = _reflection.GeneratedProtocolMessageType('GetStoreItemsResponse', (_message.Message,), dict(

  StoreItem = _reflection.GeneratedProtocolMessageType('StoreItem', (_message.Message,), dict(

    TagsEntry = _reflection.GeneratedProtocolMessageType('TagsEntry', (_message.Message,), dict(
      DESCRIPTOR = _GETSTOREITEMSRESPONSE_STOREITEM_TAGSENTRY,
      __module__ = 'POGOProtos.Networking.Platform.Responses_pb2'
      # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.StoreItem.TagsEntry)
      ))
    ,
    DESCRIPTOR = _GETSTOREITEMSRESPONSE_STOREITEM,
    __module__ = 'POGOProtos.Networking.Platform.Responses_pb2'
    # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse.StoreItem)
    ))
  ,
  DESCRIPTOR = _GETSTOREITEMSRESPONSE,
  __module__ = 'POGOProtos.Networking.Platform.Responses_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Platform.Responses.GetStoreItemsResponse)
  ))
_sym_db.RegisterMessage(GetStoreItemsResponse)
_sym_db.RegisterMessage(GetStoreItemsResponse.StoreItem)
_sym_db.RegisterMessage(GetStoreItemsResponse.StoreItem.TagsEntry)

SendEncryptedSignatureResponse = _reflection.GeneratedProtocolMessageType('SendEncryptedSignatureResponse', (_message.Message,), dict(
  DESCRIPTOR = _SENDENCRYPTEDSIGNATURERESPONSE,
  __module__ = 'POGOProtos.Networking.Platform.Responses_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Platform.Responses.SendEncryptedSignatureResponse)
  ))
_sym_db.RegisterMessage(SendEncryptedSignatureResponse)


_GETSTOREITEMSRESPONSE_STOREITEM_TAGSENTRY.has_options = True
_GETSTOREITEMSRESPONSE_STOREITEM_TAGSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
